# docker-compose
version: '3'
services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      RDS_HOST: ${RDS_HOST}
      RDS_PORT: ${RDS_PORT}
      RDS_USER: ${RDS_USER}
      RDS_PASSWORD: ${RDS_PASSWORD}
      RDS_DB_NAME: ${RDS_DB_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    restart: always